name: RunCIWorkflow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build Project
      run: dotnet build --no-restore
    
    - name: Run Unit Tests
      run: dotnet test --no-build --no-restore --verbosity normal --filter Tests.Unit
      env:
        ASPNETCORE_ENVIRONMENT : Staging

    - name: Run Integration Tests
      run: dotnet test --no-build --verbosity normal --filter Tests.Integration
      env:
        ASPNETCORE_ENVIRONMENT : Staging

    - name: Publish Project
      run: dotnet publish
      
    - name: Upload Project Artifact
      uses: actions/upload-artifact@v2
      with:
        name: TDD_Academy_Artifact
        path: /home/runner/work/TDD-Academy/TDD-Academy/source/Academy.Presentation/bin/Debug/net5.0/publish/
        
        
    - name: FTP Deployer
      uses: sand4rt/ftp-deployer@v1.1
      with:
        # FTP host URL like: ftp.host.com
        host: 185.88.152.195
        username: 1768_tdd
        password: 123456
        # The remote folder location of your FTP server
        # remote_folder: # optional
        # The local folder location
        local_folder: /home/runner/work/TDD-Academy/TDD-Academy/source/Academy.Presentation/bin/Debug/net5.0/publish/
        # Remove existing files inside FTP remote folder
        cleanup: true
        # includes
        # include: # optional
        # exclude
        # exclude: # optional
        # passive
        # pasive: # optional
