name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: PowerShell script
      uses: Amadevus/pwsh-script@v2.0.1
      with:
        script: ./build.ps1
        
        
